#!/bin/bash
set -x

PKG_BUILD_NAME=$1
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})
PKG_DIR="portieris-helm"
STX_BASE=$(realpath ${MY_REPO}/stx)
SRC=$(realpath ${STX_BASE}/portieris-armada-app/${PKG_DIR})

mkdir -p ${PKG_BUILD_ROOT}
pushd ${PKG_BUILD_ROOT}

# Local mirror workaround until CGCS_BASE mirror is supported.
STX_MIRROR=$(realpath "/import/mirrors/starlingx")

# Download portieris source package.
PORTIERIS_PKG="portieris-0.7.0.tgz"
PORTIERIS_SRC_PATH=$(realpath ${STX_MIRROR}/downloads/${PORTIERIS_PKG})
cp ${PORTIERIS_SRC_PATH} ${PKG_BUILD_ROOT}

# Extract the portieris tar file.
tar xfz ${PORTIERIS_PKG}

# Copy source files to the build directory.
cp -pr ${SRC}/files/* ${PKG_BUILD_ROOT}
