---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: portieris-certs
data:
  chart_name: portieris-certs
  release: portieris-certs
  namespace: portieris
  wait:
    timeout: 30
    native:
      enabled: true
    resources: []
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  source:
    type: tar
    location: http://172.17.0.1/helm_charts/starlingx/portieris-certs-0.1.0.tgz
    subpath: portieris-certs
    reference: master
  dependencies: []
  values:
    caCert: ""
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: portieris
data:
  chart_name: portieris
  release: portieris
  namespace: portieris
  wait:
    timeout: 300
    labels:
      app: portieris
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  source:
    type: tar
    location: http://172.17.0.1/helm_charts/starlingx/portieris-0.7.0.tgz
    subpath: portieris
    reference: master
  dependencies: []
  values:
    replicaCount: 1
    namespace: portieris
    images:
      tags:
        portieris: docker.io/starlingx/portieris:master-centos-stable-latest
    image:
      host: registry.local:9001/docker.io/starlingx
      image: portieris
      tags: master-centos-stable-latest
      tag: master-centos-stable-latest
    IBMContainerService: false
    SkipSecretCreation: true
    UseCertManager: true
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: portieris-charts
data:
  description: "StarlingX Portieris"
  sequenced: true
  chart_group:
    - portieris-certs
    - portieris
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: portieris-manifest
data:
  release_prefix: 'stx'
  chart_groups:
    - portieris-charts
