#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: portieris
  labels:
    chart_group: portieris-charts
spec:
  releaseName: portieris-portieris
  chart:
    spec:
      chart: portieris
      version: REPLACE_HELM_CHART_VERSION
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: portieris-static-overrides
      valuesKey: portieris-static-overrides.yaml
    - kind: Secret
      name: portieris-system-overrides
      valuesKey: portieris-system-overrides.yaml
