apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: null
  name: portieris-certs
  namespace: portieris
spec:
  dnsNames:
  - portieris.portieris.svc
  issuerRef:
    name: stx-portieris
  secretName: portieris-certs
status: {}
