#
# Copyright (c) 2018 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# Default values for nova-api-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

caCert: ""